fieldLayouts:
  47f8b029-db1d-4177-94d5-430d3a41130e:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: services
name: Services
siteSettings:
  6de046f0-6167-4af1-aa91-ffaf83e36a14: # NL
    hasUrls: true
    template: null
    uriFormat: 'services/{slug}'
  e57cf13b-f9cb-484a-8093-a897fa43eb68: # EN
    hasUrls: true
    template: null
    uriFormat: 'services/{slug}'
  fd2014b7-5bc0-49a9-ac30-e009081532f7: # FR
    hasUrls: true
    template: null
    uriFormat: 'services/{slug}'
structure:
  maxLevels: null
  uid: e0dd354e-aa58-4d91-8ffe-ccf60a571771
