contentColumnType: string
fieldGroup: a49c69b9-ced8-415b-a23a-f0589358d3b6 # Categories
handle: articleType
instructions: ''
name: 'Article Type'
searchable: true
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  branchLimit: ''
  limit: null
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: false
  source: 'group:d9ce912d-acfb-4315-a0a4-fcb07ba8fa22' # Article Type
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
