contentColumnType: string
fieldGroup: 767fbb17-acfa-4071-97b2-54e2c728dd4b # Event upcoming
handle: ctaBanner
instructions: ''
name: 'CTA Banner'
searchable: true
settings:
  contentTable: '{{%matrixcontent_ctabanner}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
