contentColumnType: text
fieldGroup: 0400ee8d-766a-4c77-9d53-814333021b57 # Scientific Committee
handle: function
instructions: ''
name: Function
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
