contentColumnType: text
fieldGroup: 0cc15eea-0b40-4abb-b128-75eeaa8d5907 # Detail Expert
handle: housenumber
instructions: ''
name: Housenumber
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
