contentColumnType: text
fieldGroup: 3a08910b-137a-497e-aea4-44fe0937bcc7 # Knowledge Detail
handle: nameSpeaker
instructions: ''
name: 'Name Speaker'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
