contentColumnType: integer(10)
fieldGroup: 767fbb17-acfa-4071-97b2-54e2c728dd4b # Event upcoming
handle: practicalInfoPrice
instructions: ''
name: 'Practical Info Price'
searchable: true
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: '0'
  prefix: null
  previewCurrency: ''
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
